#! python


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features='run_py_script',
        source='timing.py',
        deps=[
              ctx.path_to(ctx,'IN_DATA','Bild_Training.xlsx'),
              ctx.path_to(ctx,'IN_MODEL_CODE','test_update.py')
             ],
        target= [
                ctx.path_to(ctx, "OUT_DATA", "all_articles.xlsx"),
                ctx.path_to(ctx, "OUT_DATA", "training.xlsx")
                ]
        #name='runtimes'
    )
