#! python

def build(ctx):
    #abspath = os.path.join(ctx.path.abspath(), 'test_update.py')
    ctx(
        features='run_py_script',
        source='test_update.py',
        deps='update.py'
        #append=abspath
        )